language: node_js
node_js:
  - '14'
dist:
  - trusty
services:
  - mongodb
  - redis
env:
  - PORT=3000
  - NODE_ENV=ci
cache:
  directories: - node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
